--Author Frankie boi--
DROP TABLE IF EXISTS Referrals CASCADE;

DROP TABLE IF EXISTS Reference_Conditions CASCADE;

DROP TABLE IF EXISTS Ref_Indiv_Condition CASCADE;

DROP TABLE IF EXISTS Ref_Household_Info CASCADE;

DROP TABLE IF EXISTS Other_Agencies CASCADE;

DROP TABLE IF EXISTS Participants CASCADE;

DROP TABLE IF EXISTS Curriculum CASCADE;

DROP TABLE IF EXISTS Class_Subjects CASCADE;

DROP TABLE IF EXISTS Curriculum_Subjects CASCADE;

DROP TABLE IF EXISTS Employees CASCADE;

DROP TABLE IF EXISTS Locations CASCADE;

DROP TABLE IF EXISTS Classes_Scheduled CASCADE;

DROP TABLE IF EXISTS Class_Attendence CASCADE;

DROP TABLE IF EXISTS Consent_to_Release_Info CASCADE;

DROP TABLE IF EXISTS Participant_Intake CASCADE;

DROP TABLE IF EXISTS Intk_Children CASCADE;
